### ISSUE TITLE
导师评价内容

### ISSUE THREAD

**Issue by cmdllx** [kgco/RateMySupervisor#10]
想问一下这个项目是静态的吗
感觉导师评价网上出了新的评论但是这个项目中没有更新？

**Comment by moji111** [comment]
可能是因为 新的评价需要收费了 就没法爬取暂时。。？

**Comment by cmdllx** [comment]
理解了，感觉github上建一个导师评价网挺好的


cczhou
chenmodechenchen@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kgco/RateMySupervisor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 下午2:26
收件人:&nbsp;"kgco/RateMySupervisor"<RateMySupervisor@noreply.github.com&gt;;
抄送:&nbsp;"沉默"<1658802578@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kgco/RateMySupervisor] 导师评价内容 (#10)





 
可能是因为 新的评价需要收费了 就没法爬取暂时。。？

**Comment by kgco** [comment]
项目是静态的，原计划为不影响网站运转半年爬取一次，没想到网站已经关闭了，详情看issue #13

**Comment by cmdllx** [comment]
明白了，作者辛苦了




cczhou
chenmodechenchen@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kgco/RateMySupervisor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月27日(星期二) 上午9:22
收件人:&nbsp;"kgco/RateMySupervisor"<RateMySupervisor@noreply.github.com&gt;;
抄送:&nbsp;"沉默"<1658802578@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kgco/RateMySupervisor] 导师评价内容 (#10)





 
项目是静态的，原计划为不影响网站运转半年爬取一次，没想到网站已经关闭了，详情看issue #13
