### ISSUE TITLE
用这些数据建了个网站，欢迎大家试用

### ISSUE THREAD

**Issue by qxzzxq** [kgco/RateMySupervisor#16]

**Comment by qxzzxq** [comment]
目前检索和新增评论的功能已经上线。支持匿名评论。

正在添加评论versioning，和点赞/踩功能

**Comment by qxzzxq** [comment]
评论修改记录查询已经上线，对于被修改过的记录，只要点击最近编辑日期就可以查看历史记录
![image](https://user-images.githubusercontent.com/17144939/102867646-5aac5480-4439-11eb-8d37-a941745abba3.png)

**Comment by qxzzxq** [comment]
换了新域名[yankong.org](https://www.yankong.org)

**Comment by qxzzxq** [comment]
最近事情比较多，争取二月初上线点赞功能

**Comment by wangzhiye-tiancai** [comment]
@kgco @qxzzxq 
如果是我选导师，对着下拉菜单一个个拉多难受，都列出来多好
而且，别人没法通过百度谷歌搜索学校和导师的名字直接找到你们这里

**Comment by kgco** [comment]
> @kgco @qxzzxq
> 如果是我选导师，对着下拉菜单一个个拉多难受，都列出来多好
> 而且，别人没法通过百度谷歌搜索学校和导师的名字直接找到你们这里

我这个页面的确缺个搜索功能，最近实在太忙了，如果需要回头我会做，你可以开个issue。现阶段如果在我这里需要搜索功能可以直接去[json文件](https://github.com/kgco/RateMySupervisor/blob/master/data/comments_data.json)里搜索，先凑合一下😂。

**Comment by qxzzxq** [comment]
@kgco @wangzhiye-tiancai 嗯有道理👍  我也应该弄一下SEO，让搜索引擎能直接搜到老师。

至于列出全部老师的名字，我觉得不一定有这个必要。应该没有人会仅根据导师的评价选导师。我觉得更可能的情况是：用户已经有了一个自己中意的导师名单，然后会根据这个名单查找一下导师们的评价做为辅助信息。直接在搜索框里输入可能更快。

**Comment by wangzhiye-tiancai** [comment]
@kgco 
> 至于被搜索引擎收录的事，回头我可以去google的index里把GitHub Pages页面扔进去

@qxzzxq 
> 至于列出全部老师的名字，我觉得不一定有这个必要

我的意思是，要让学生**在搜索引擎搜索导师名字**能够链接到这里，那么每个导师至少要有个单独url和单独页面

这还不够，还需要外链，所以列出来是难免的。蜘蛛可不会爬下拉列表里藏着的链接

**Comment by qxzzxq** [comment]
> > 至于列出全部老师的名字，我觉得不一定有这个必要
> 
> 我的意思是，要让学生**在搜索引擎搜索导师名字**能够链接到这里，那么每个导师至少要有个单独url和单独页面
> 
> 这还不够，还需要外链，所以列出来是难免的。蜘蛛可不会爬下拉列表里藏着的链接

@wangzhiye-tiancai 嗯嗯这个在搞了:+1:，现在每个老师已经有了自己单独的url。我正在准备search engine optimisation

**Comment by qxzzxq** [comment]
发现一个问题：貌似百度，bing跟其它很多蜘蛛对SPA的支持都不是很好。我的网站是angular写的，这些蜘蛛都没法运行html里的js代码。

Google的crawler是可以的。

**Comment by kaisxu** [comment]
@qxzzxq  有计划开源嘛？可以帮忙一起开发😁

**Comment by qxzzxq** [comment]
@kaisxu 网站代码为了安全起见还是不开源了，暂时只开源数据。

非常欢迎，你可以加这个slack群，我们私聊一下
https://join.slack.com/t/w1612834170-a1i198982/shared_invite/zt-m29ssuqa-50j1IFYPNnQTfYhdjeb9yw

@wangzhiye-tiancai @kgco 如果你们感兴趣的话也欢迎加入

**Comment by mysupervisor** [comment]
你凭什么使用来自原导师评价网的数据？经过人家同意了吗？

**Comment by charfole** [comment]
@qxzzxq 
你好，最近发现研控注册的时候有 bug，提示 **“An error was encountered with the requested page”**，不知道是什么问题呢？

**Comment by qxzzxq** [comment]
> @qxzzxq
> 你好，最近发现研控注册的时候有 bug，提示 **“An error was encountered with the requested page”**，不知道是什么问题呢？

@charfole 我也发现这个问题了，我检查一下

**Comment by 3k9** [comment]
@charfole 我们新建了一个issue，你可以在https://github.com/the-realm-of-research/ror-issue/issues/1 跟踪这个issue的进度

**Comment by 3k9** [comment]
@charfole 我们新建了一个issue，你可以在the-realm-of-research/ror-issue#1 跟踪这个issue的进度

**Comment by wangzhiye-tiancai** [comment]
@qxzzxq 感谢邀请
slack以前我们没玩过，得有时间学学

**Comment by qxzzxq** [comment]
@wangzhiye-tiancai 好的之前的链接过期了，如果你们想参加讨论的话就给realmofresearch.contact@gmail.com发个邮件，我再加你们:D
