### ISSUE TITLE
建议搭建telegram机器人

### ISSUE THREAD

**Issue by 0warning0error** [kgco/RateMySupervisor#21]
tg机器人不需要复杂的逻辑，只需要实现后端功能，且有Python库直接搭建机器人，减少真实身份被爆出的可能性。而且提交评价只需要自己登陆tg账号给机器人提交就行，找个时间然后统一添加审核

**Comment by kgco** [comment]
现在已经有不少人基于这个repo建站啦，所以暂时不准备搞啦，这里数据也暂时停止更新啦，大家可以下载数据用来备份
