### ISSUE TITLE
未经原导师评价网同意，就发布源自此网站的数据，是否侵权

### ISSUE THREAD

**Issue by mysupervisor** [kgco/RateMySupervisor#22]
urfire.com未经允许大规模爬取并且发布原导师评价网的部分数据。

现urfire.com已经关闭。

此处的数据的爬取和发布是否经过原导师评价网同意？

数据来自原导师评价网，这个repo有何权利进行发布？是否侵权？

**Comment by hijkzzz** [comment]
数据属于用户~不属于导师评价网 而且已经被墙了

**Comment by skybush** [comment]
本来就是UGC的东西，哪来的侵权一说？
