### ISSUE TITLE
部分导师信息没有

### ISSUE THREAD

**Issue by ridewindgo** [kgco/RateMySupervisor#3]
目前看了，整个中山大学的导师数据都是缺失的，南京大学窦万春老师，等等也没出现。

**Comment by kgco** [comment]
我查了一下，目前数据来源主要是[导师推荐网](https://www.urfire.com/)，这是该网站的数据缺失：

- [导师推荐网-南京大学](https://www.urfire.com/school/2389)页面没有窦万春老师的数据
- [导师推荐网-中山大学](https://www.urfire.com/school/2747)页面没有教师数据

具体原因不得而知，如有其他可靠信息来源欢迎补充，我来写爬虫；
若有自己的评价信息可以前往[这条issue](https://github.com/kgco/RateMySupervisor/issues/1)添加信息。

**Comment by kgco** [comment]
我突然意识到一个问题，[导师推荐网](https://www.urfire.com/)不是我在维护，我开这个repo是为了开源存储网络上各种导师评价信息。不过目前的数据的确都是从[导师推荐网](https://www.urfire.com/)爬取的，网站维护者如果能看到我这条还请接受这个道歉，毕竟之前爬取网站数据可能为服务器带来了意料之外的压力。

所以这个repo只是为各位做备份用的，还请支持[导师推荐网](https://www.urfire.com/)，必要的时候也应该支持他们赚取广告收益，希望他们能一直做下去，如果他们网站访问不稳定或者出现其他问题再来这个repo找数据。

笔芯。

**Comment by ridewindgo** [comment]
不好意思，我看错了，我以为这个repo就是导师推荐网的数据来源， 事实这个repo是导师推荐网的数据存档和备份。

**Comment by ridewindgo** [comment]
微信有一个小程序叫“导师印象”，里面数据不算全，也算一个数据来源之一，您可以看看。

**Comment by kgco** [comment]
感谢反馈数据来源~

**Comment by 7omato** [comment]
没搞懂urfire与这ratemysupervisorOrg网站的关系，前者是爬的后者吗
但是后者里面是有中大的  [www.ratemysupervisor.org/forum/view/850 ](url)
数据缺失很遗憾，正好目的是查中大
