### ISSUE TITLE
为什么找不到云南大学？是云大不够格吗？

### ISSUE THREAD

**Issue by fangbincheng** [kgco/RateMySupervisor#31]
云南大学始建于1922年，时为私立东陆大学，1934年更名为省立云南大学，1938年改为国立云南大学，是中国西部边疆最早建立的综合性大学之一。1946年，《不列颠百科全书》将云南大学列为中国15所在世界最具影响的大学之一。1958年，云南大学由中央高教部划归云南省管理。1978年，云南大学被国务院确定为全国88所重点大学之一。1996年首批列入国家“211工程”重点建设大学。1999年，云南政法高等专科学校并入云南大学。2017年成为中国首批42所“世界一流大学”建设高校之一。

**Comment by kgco** [comment]
Duplicate of #3

**Comment by kgco** [comment]
这里只存储原来导师评价网的部分用户评价信息，数据来源不是我说了算的。但是我以为我辛辛苦苦无偿维护这个repo好歹是可以得到尊重的，至少是再语气上，而不是在这里阴阳怪气。
