### ISSUE TITLE
[Bug]页面导航错误

### ISSUE THREAD

**Issue by DawnMagnet** [kgco/RateMySupervisor#33]
http://daoshidianping.com/#/college?uni_id=14 页面中的“土地与科学技术学院项目”，会将页面导航至 http://daoshidianping.com/#/teacher?school_id=991 武汉大学。

**Comment by kgco** [comment]
这个Repo不是daoshidianping.com的Repo，后者的维护者另有其人。这里只是导师评价数据的开放Repo
