### ISSUE TITLE
[feature request]更改评价展示的顺序

### ISSUE THREAD

**Issue by Pzoom522** [kgco/RateMySupervisor#4]
感谢作者在原“导师评价网”开始恰烂钱后，挺身而出维护这个积功德的项目！:bouquet:
目前的导师评价，默认是时间顺序——旧评价在前，新评价在后。下面三种顺序可能更好：

- **时间倒序**：逆序排列，易于实现且更加合理（新评价时效性更好）
- **字数倒序**：越长的评价越靠前。一般来说，长评价更认真，信息量更大，更有价值
- **点评顺序**：未来不妨增加赞/踩功能，高分评价优先展示。但是可能需要考虑防范水军的问题

**Comment by kgco** [comment]
感谢建议，已经在[最新的commit](https://github.com/kgco/RateMySupervisor/commit/c8b78bbf8714542ef060b3c4841b9eea5884abca)中加入了排序功能的更新：
- 在`urfire.py`中为数据添加了时间信息和字数信息
- 在`index.html`中新增了时间顺序/倒序，评价顺序/倒序，字数倒序的排序功能

另外，增加「赞/踩」功能问题很多，目前不考虑添加，原因有这些：
- 就像你说的，水军问题，基本是无法防范的
- 这个在GitHub的repo主要用于数据存储和展示，数据收集是万不得已时才用的功能（其他导师评价网站都已长期关闭）
- 收集「赞/踩」数据在GitHub实现起来比较麻烦
