### ISSUE TITLE
导师的某条评价有明显的人身攻击，且与事实不符，可否提个MR删除？

### ISSUE THREAD

**Issue by microhhh** [kgco/RateMySupervisor#44]
例如评价
"id": 3367,
"teacher_id": 397,
早期的评论有很明显的夸大，以及攻击。近几年的情况学院的同学和很多公开材料都可以证明。

**Comment by kgco** [comment]
我十分理解您的心情，这里的评价数据也极有可能有一些有失公允的评价，但是十分抱歉，您不能提起一个**删除某个评价**的request。

简而言之，作为repo所有者的我和任何一个contributor都没有能力核查具体某条评论的真实性，哪怕它实际上的确明显失事，因此我决定杜绝一切不可逆的数据操作。相关问题已有较多讨论，你可以参见[Readme的相关部分](https://github.com/kgco/RateMySupervisor#%E5%85%B3%E4%BA%8E%E8%B4%A1%E7%8C%AE%E6%96%B0%E4%BF%A1%E6%81%AF)以及 #35 。

因此，欢迎您提起在相关导师下添加评论的PR，我可以merge它进来，或者任何[Readme的操作方法部分提到的操作](https://github.com/kgco/RateMySupervisor#%E6%93%8D%E4%BD%9C%E6%96%B9%E6%B3%95)。

最后要再说一次，感谢每一位希望对本项目做出贡献的朋友，这样做不是对您的信息不信任，只是作为以往大量导师评价信息的最后一块保留地，作为repo维护者的我只能谨慎再谨慎，十分抱歉！

**Comment by microhhh** [comment]
好的感谢回复
