### ISSUE TITLE
能否补充研究所的信息？

### ISSUE THREAD

**Issue by wenzhilics** [kgco/RateMySupervisor#9]
能否补充研究所信息？研究机构内容不全。多谢~~

**Comment by kgco** [comment]
抱歉，信息全不全取决于数据来源，目前我们目前的数据来源（早先的导师评价网，以及目前的导师推荐网）尚没有很完整的研究机构数据。如果有相关数据来源，欢迎提供给我。

**Comment by wenzhilics** [comment]
多谢回复！研究所的数据不全。如 https://ratemysupervisor.org/Forum/View/4418 中的每个所。期待增加此数据！

**Comment by moji111** [comment]
http://www.cas.cn/zz/index.shtml#hs_zzjg在这个页面的下方有中科院的研究单位 应该涵盖了绝大部分可以招收研究生的所~希望可以给一点建议~

**Comment by kgco** [comment]
> [http://www.cas.cn/zz/index.shtml#hs_zzjg在这个页面的下方有中科院的研究单位](http://www.cas.cn/zz/index.shtml#hs_zzjg%E5%9C%A8%E8%BF%99%E4%B8%AA%E9%A1%B5%E9%9D%A2%E7%9A%84%E4%B8%8B%E6%96%B9%E6%9C%89%E4%B8%AD%E7%A7%91%E9%99%A2%E7%9A%84%E7%A0%94%E7%A9%B6%E5%8D%95%E4%BD%8D) 应该涵盖了绝大部分可以招收研究生的所~希望可以给一点建议~

在`data\ufire.json`下有完整的各科研机构的清单，只是大部分机构单位中没有评价信息，因此没有列在最终展示的界面中。

**Comment by kgco** [comment]
> 多谢回复！研究所的数据不全。如 https://ratemysupervisor.org/Forum/View/4418 中的每个所。期待增加此数据！

此数据可以在`data\ufire.json`中查到，没有检索到内容是因为大部分机构没有导师评价信息，因此在最终的界面中没有显示。要想使用UI检索这一信息，可以：
- 将`src\html_render.py`中第一行修改为`with open('data/urfire.json', 'r',encoding='utf8') as f:`
- 运行该文件
- 重新打开`html\index.html`即可
